# Example item, with default values
# [[item]]
# file = '~/.config/example' (required)
# template = 'example' (required)
# subtemplate = 'default'
# rewrite = false
# start = '# Start flavours'
# end = '# End flavours'
# hook = ''

[[item]]
file = '~/.config/sway/border.svg'
template = 'svg-circle'
rewrite = true
hook = 'renderborder'

[[item]]
file = '~/.config/alacritty/alacritty.yml'
template = 'alacritty'
subtemplate = 'default-256'

[[item]]
file = '~/.config/qutebrowser/config.py'
template = 'qutebrowser'
subtemplate = 'minimal'
hook = 'reloadqb'

[[item]]
file = '~/.config/sway/config'
template = 'sway'
subtemplate = 'colors'
rewrite = false

[[item]]
file = '~/.themes/FlatColor/colors3'
template = 'gtk-flatcolor'
subtemplate = 'gtk-3'
rewrite = true
hook = 'bash -c "gsettings set org.gnome.desktop.interface gtk-theme FlatColor && gsettings set org.gnome.desktop.interface gtk-theme dummy"'

[[item]]
file= '~/.config/zathura/zathurarc'
template = 'zathura'
rewrite = false

[[item]]
file = '~/.themes/FlatColor/colors2'
template = 'gtk-flatcolor'
subtemplate = 'gtk-2'
rewrite = true

[[item]]
file = '~/.colors'
template = 'bash'
rewrite = true
hook = 'systemctl --user restart rgbdaemon'

[[item]]
file = '~/.config/waybar/colors.css'
template = 'waybar'
rewrite = true

[[item]]
file = '~/.config/beautifuldiscord/style.css'
template = 'styles'
subtemplate = 'css-variables'
rewrite = false
start= '/* Start flavours */'
end = '/* End flavours */'
